### ISSUE TITLE
Documentation is not deployed

### ISSUE THREAD

**Issue by hyrodium** [JuliaLangSlack/Slack.jl#10]
* There's no deployed docs in `gh-pages` branch.
* These links should be updated:
![image](https://user-images.githubusercontent.com/7488140/128595901-6cd05321-1485-40d0-9834-1c13b8d4c40f.png)
![image](https://user-images.githubusercontent.com/7488140/128595922-bb133e55-8d4c-495e-a7a4-03b683e7cbb0.png)

**Comment by logankilpatrick** [comment]
Good catch, the repo was moved around to a new org so the links needed to be updated: https://github.com/JuliaLangSlack/Slack.jl/commit/a77262b17d1632c985070adcff8fb317ce410e0a
