### ISSUE TITLE
Feature request: add a wrapper to get conversation history

### ISSUE THREAD

**Issue by asinghvi17** [JuliaLangSlack/Slack.jl#9]
I'd like to be able to back up a couple of private channels, perhaps posting them on Github.  

https://api.slack.com/methods/conversations.history#response shows that this is possible, with a little effort :D.  If you can provide the API endpoint, I could do the rest.

**Comment by logankilpatrick** [comment]
I will have this done soon. I haven't had time until yesterday's hackathon and it's almost complete. 

b366acfc250e717375a9021dc53f65ba4220f1d2

**Comment by logankilpatrick** [comment]
This is possible now @asinghvi17
